export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}", "./desktop-ui/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        anubis: {
          canvas: "#f5f5f4",
          surface: "#ffffff",
          sidebar: "#fbfbfa",
          elevated: "rgba(255, 255, 255, 0.92)",
          border: "#e5e5e1",
          "border-soft": "#eeeeea",
          "text-strong": "#171717",
          text: "#242424",
          muted: "#73726d",
          subtle: "#a4a29b",
          hover: "#f0efeb",
          active: "#ffffff",
          "active-bar": "#1f1f1d",
          code: "#121212",
          "code-border": "#2c2c2a",
          "code-text": "#f4f4ef",
          input: "#fafaf8",
          focus: "rgba(37, 37, 34, 0.08)",
          "focus-border": "#b9b8b2",
          overlay: "rgba(20, 20, 18, 0.24)",
          control: "#222220",
          "control-hover": "#343431",
          "control-stop": "#45443f",
          "control-stop-hover": "#57554f",
        },
      },
      fontFamily: {
        ui: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        code: [
          "SFMono-Regular",
          "SF Mono",
          "Consolas",
          "Liberation Mono",
          "Menlo",
          "monospace",
        ],
      },
      borderRadius: {
        "anubis-sm": "8px",
        "anubis-md": "10px",
        anubis: "14px",
        "anubis-lg": "16px",
      },
      boxShadow: {
        anubis: "0 16px 44px rgba(20, 20, 18, 0.06), 0 1px 2px rgba(20, 20, 18, 0.04)",
        "anubis-popover": "0 28px 84px rgba(20, 20, 18, 0.18), 0 0 0 1px rgba(20, 20, 18, 0.06)",
      },
      spacing: {
        "anubis-1": "4px",
        "anubis-2": "8px",
        "anubis-3": "12px",
        "anubis-4": "16px",
        "anubis-5": "20px",
        "anubis-6": "24px",
        "anubis-8": "32px",
        sidebar: "244px",
      },
    },
  },
  plugins: [],
};
